### ISSUE TITLE
Salary range reduction seems like a bug 😅

### ISSUE THREAD

**Issue by khadni** [Cyfrin/OpenPositions#1]
**Describe the bug**
I've noticed that in the recent commit for the Senior Security Researcher position at Cyfrin, the expected salary range was changed from $210-300K USD to $110-250K USD. I believe this must be an error in the repo code, as it's quite a significant reduction.

**To Reproduce**

Go to the `senior_security_engineer.md` file
Check the salary range before and after the commit from the owner

**URLs**
[Senior Security Researcher position](https://github.com/ChainAccelOrg/OpenPositions/blob/main/senior_security_engineer.md)

**Expected behavior**
Considering the high level of expertise required for a Senior Security Researcher position, I was expecting the salary range to remain the same or even increase. The reduction seems to be a mistake and should be corrected.

**Additional context**
This issue is intended as a light-hearted joke, but I wanted to bring it to your attention, just in case it was an unintentional change.

**Comment by PatrickAlphaC** [comment]
Ahah. Thanks for the issue. It was an intentional change.
